name: APC_project
channels:
  - conda-forge
dependencies:
  - black
  - cattrs
  - folium
  - geopandas
  - ipykernel >=6.0
  - ipython >=8.0
  - ipywidgets
  - jupyter-book
  - jupyterlab >=3
  - matplotlib >=3.5
  - mypy >=0.981
  - nb_conda_kernels
  - numba
  - numpy >=1.20
  - pandas >=1.3
  - pip
  - pytest >7
  - python ==3.10.*
  - rich >=11
  - shapely
  - sphinxcontrib-mermaid
  - typing
  - wikipedia
